# Building a Prod-Ready, Robust Shiny Application.
#
# README: each step of the dev files is optional, and you don't have to
# fill every dev scripts before getting started.
# 01_start.R should be filled at start.
# 02_dev.R should be used to keep track of your development during the project.
# 03_deploy.R should be used once you need to deploy your app.
#
#
########################################
#### CURRENT FILE: ON START SCRIPT #####
########################################

## Fill the DESCRIPTION ----
## Add meta data about your application
##
## /!\ Note: if you want to change the name of your app during development,
## either re-run this function, call golem::set_golem_name(), or don't forget
## to change the name in the app_sys() function in app_config.R /!\
##
golem::fill_desc(
  pkg_name = "MetMiner", # The Name of the package containing the App
  pkg_title = "MetMiner: A user-friendly pipeline for large-scale plant metabolomics data analysis", # The Title of the package containing the App
  pkg_description = "The utilization of metabolomics approaches to explore the metabolic mechanisms underlying plant fitness and adaptation to dynamic environments is growing, highlighting the need for an efficient and user-friendly toolkit tailored for analyzing the extensive datasets generated by metabolomics studies. Current protocols for metabolome data analysis often struggle with handling large-scale datasets or require programming skills. To address this, we present MetMiner (https://github.com/ShawnWx2019/MetMiner), a user-friendly, full-functionality pipeline specifically designed for plant metabolomics data analysis. Built on R shiny, MetMiner can be deployed on servers to utilize additional computational resources for processing large-scale datasets. MetMiner ensures transparency, traceability, and reproducibility throughout the analytical process. Its intuitive interface provides robust data interaction and graphical capabilities, enabling users without prior programming skills to engage deeply in data analysis. Additionally, we constructed and integrated a plant-specific mass spectrometry database into the MetMiner pipeline to optimize metabolite annotation. We have also developed MDAtoolkits, which include a complete set of tools for statistical analysis, metabolite classification, and enrichment analysis, to facilitate the mining of biological meaning from the datasets. Moreover, we propose an iterative weighted gene co-expression network analysis strategy for efficient biomarker metabolite screening in large-scale metabolomics data mining. In two case studies, we validated MetMiner's efficiency in data mining and robustness in metabolite annotation. Together, the MetMiner pipeline represents a promising solution for plant metabolomics analysis, providing a valuable tool for the scientific community to use with ease.", # The Description of the package containing the App
  author_first_name = "Xiao", # Your First Name
  author_last_name = "Wang", # Your Last Name
  author_email = "shawnwang2016@126.com", # Your Email
  repo_url = NULL, # The URL of the GitHub Repo (optional),
  pkg_version = "1.0.1" # The Version of the package containing the App
)

## Set {golem} options ----
golem::set_golem_options()

## Install the required dev dependencies ----
golem::install_dev_deps()

## Create Common Files ----
## See ?usethis for more information
usethis::use_mit_license("Golem User") # You can set another license here
usethis::use_readme_rmd(open = FALSE)
devtools::build_readme()
# Note that `contact` is required since usethis version 2.1.5
# If your {usethis} version is older, you can remove that param
usethis::use_code_of_conduct(contact = "Golem User")
usethis::use_lifecycle_badge("Experimental")
usethis::use_news_md(open = FALSE)

## Use git ----
usethis::use_git()

## Init Testing Infrastructure ----
## Create a template for tests
golem::use_recommended_tests()

## Favicon ----
# If you want to change the favicon (default is golem's one)
golem::use_favicon() # path = "path/to/ico". Can be an online file.
# golem::remove_favicon() # Uncomment to remove the default favicon

## Add helper functions ----
golem::use_utils_ui(with_test = TRUE)
golem::use_utils_server(with_test = TRUE)

# You're now set! ----

# go to dev/02_dev.R
rstudioapi::navigateToFile("dev/02_dev.R")
