#' @title mda_make_keggdb
#' @description Different accumulation analysis
#' @author Shawn Wang <http://www.shawnlearnbioinfo.top>.
#' \email{shawnwang2016@@126.com}
#' @param x 'Dataframe' or 'matrix'; Peak area file contains all sample.
#' @param left_index 'characters'; The first sample set names corresponding to the peak area matrix
#' @param right_index 'characters'; The second sample set names corresponding to the peak area matrix
#' @param left 'characters'; The group name of first sample
#' @param right 'characters'; The group name of first sample
#' @param method 'characters'; t-test or anova-test. default is t-test.
#' @param method2 'characters'; pls-da or opls-da. default is opls-da.
#' @return A list; MDA_tbl is a dataframe contains all compounds and all DAM judge values include log2fc,pvalue,FDR and FDR. opls_out is opls_da result generated by ropls package.
#' @importFrom dplyr select mutate group_by summarise arrange distinct
#' @importFrom tidyr replace_na nest unnest
#' @importFrom purrr map2_chr
#' @importFrom crayon green red blue yellow
#' @importFrom ropls opls getVipVn 
#' @importFrom rstatix t_test anova_test
#' @export
#' @examples 
#' \dontrun{
#' # set param
#' mat = step7_result %>% select("CompoundID",starts_with("sample")) %>% as.matrix
#' left_index = c("sample_01","sample_02","sample_03")
#' right_index = c("sample_04","sample_05","sample_06")
#' left = "case"
#' right = "control"
#' DM_analysis(x = mat,left_index,right_index,left,right)
#' }
#' 
library(clusterProfiler)
library(tidyverse)
library(conflicted)
library(RCurl)
library(crayon)
conflict_prefer_all("dplyr")

anno <- readxl::read_xlsx("02.DemoData/compound_anno.xlsx",sheet = 1)
kegg.plant <- read.table("/Users/shawn/GeekCloud/01.Database/TBtools.Plant.KEGG.backEnd.20200724",sep = "\t",header = F)

library(progressr) 
mda_make_keggdb <- function(organism="ath",backend = NULL){
  msg_yes = green$bold$italic;
  msg_no = red$bold$italic;
  msg_warning = yellow$bold$italic;
  message(msg_yes("Start construction kegg database of ",organism,".\nIt may take a while, please be patient!"))
  ##> functions 
  map2cid <- function(mapid){ ## map 2 cid via kegg api
    url = "https://rest.kegg.jp/link/cpd/";
    out = data.frame(
      TERM = mapid,
      CID = NA
    )
    tryCatch({
      html <- RCurl::getURL(url = paste0(url,mapid)) 
      if (html == "\n") {
        message(msg_warning(paste0(mapid," do not have corresponding cpd based on KEGG database!")))
      } else {
        out = html %>% 
          read.table(text = .,header = F) %>% 
          setNames(c("TERM","CID")) %>% 
          mutate(TERM = str_remove(TERM,'path:'),
                 CID = str_remove(CID,"cpd:"))
      }
    },error=function(e){
      message(msg_no(paste0(mapid," failed!")))
    })
    return(out)
  }
  
  mapid2cid = function(mapids) { ## map run
    x <- mapids
    p <- progressr::progressor(along = x);
    round_n = length(x);
    b = furrr::future_map2_dfr(.x = x,.y = c(1:round_n),.f = function(.x,.y) {
      Sys.sleep(0.1);
      p(sprintf("%s",paste0(.x,"(",.y,"/",round_n,")")))
      a <- map2cid(
        mapid = .x
      )
      return(a)
    });
    b <- b %>% filter(!is.na(CID))
    return(b)
  }
  #> tran format of backend
  if(organism == "special") {
    t2n1 <- 
      backend %>% select(V3) %>% 
      mutate(term = str_extract(V3,"\\d++(?= )"),
             name = str_remove(V3,"\\d++(?= )")) %>%  
      select(term,name) %>% 
      distinct()
    t2n2 <- 
      backend %>% 
      select(V4) %>% 
      mutate(V4 = str_remove(V4,"B  ")) %>% 
      mutate(term = str_extract(V4,"\\d++(?= )"),
             name = str_remove(V4,"\\d++(?= )")) %>% 
      select(term,name) %>% 
      distinct()
    t2n_merge <- rbind(t2n1,t2n2) %>% mutate(term = paste0('map',term)) %>% 
      filter(!str_detect(name,"Others|Unclassified")) %>% setNames(c("TERM","NAME"))
  } else {
    t2n_merge = getURL(paste0("https://rest.kegg.jp/list/pathway/",organism)) %>% 
      read.table(text = .,header = F,sep = "\t") %>% setNames(c("TERM","NAME")) %>% 
      mutate(TERM = str_replace(TERM,organism,"map")) %>% 
      pull(TERM) %>% ko2name() %>% setNames(c("TERM","NAME"))
  }
  mapids = t2n_merge %>% pull(TERM)
  with_progress({
    TERM2GENE = mapid2cid(mapids = mapids)
  })
  out = list(
    TERM2NAME = t2n_merge,
    TERM2GENE = TERM2GENE
  )
  message(msg_warning("「NOTIC」\nPlease save the obtained results using the save() command for long-term usage."))
  return(out)
}

ath_kegg_db <- mda_make_keggdb(organism = 'ath')
ghi_kegg_db <- mda_make_keggdb(organism = 'ghi')
zma_kegg_db  <- mda_make_keggdb(organism = 'zma')
plant_kegg_db <- mda_make_keggdb(backend = kegg.plant)
taes_kegg_db <- mda_make_keggdb(organism = 'taes')
osa_kegg_db <- mda_make_keggdb(organism = 'osa')
gmx_kegg_db <- mda_make_keggdb(organism = 'gmx')
bna_kegg_db <- mda_make_keggdb(organism = 'bna')
save(ath_kegg_db,file = "03.Document/ath_kegg_db.rda")
save(ghi_kegg_db,file = "03.Document/ghi_kegg_db.rda")
save(zma_kegg_db,file = "03.Document/zma_kegg_db.rda")
save(plant_kegg_db,file = "03.Document/plant_kegg_db.rda")
save(taes_kegg_db,file = "03.Document/taes_kegg_db.rda")
save(osa_kegg_db,file = "03.Document/osa_kegg_db.rda")
save(gmx_kegg_db,file = "03.Document/gmx_kegg_db.rda")
save(bna_kegg_db,file = "03.Document/bna_kegg_db.rda")

load("03.Document/ath_kegg_db.rda")
anno <- readxl::read_xlsx("02.DemoData/compound_anno.xlsx",sheet = 1)

query <- anno %>% 
  mutate(KEGG.ID = str_split(KEGG.ID.iso,"|",2,T)[,1]) %>% 
  filter(is.na(KEGG.ID) & !str_detect(Compound_name,"^MW:")) %>% 
  pull(Compound_name) 

library(MDAtoolkits)
library(tidyverse)
name2kegg1 <-mda_name2kegg(query = query[1:10]) %>% filter(KEGG != "")
name2kegg2 <- mda_CTS_kegg(query = query[1:10],key = 'name') %>% filter(KEGG != "")

ID2TERM = anno %>% 
  mutate(KEGG.ID = str_split(KEGG.ID.iso," | ",2,T)[,1]) %>% select(Compound_id,KEGG.ID) %>% drop_na() %>% 
  filter(!is.na(KEGG.ID)) %>% 
  filter(!KEGG.ID == "NA") %>% 
  rename("KEGG" = "KEGG.ID")
TERM2COMPOUND = ath_kegg_db$TERM2GENE %>% inner_join(ID2TERM,by = c("CID"="KEGG"),multiple = "all") %>% 
  distinct() %>% select(TERM,Compound_id)
test_c = anno$Compound_id[1:400]
library(clusterProfiler)
res.kegg <- enricher(
  gene = test_c,pvalueCutoff = 1,qvalueCutoff = 1,TERM2GENE = TERM2COMPOUND,TERM2NAME = ath_kegg_db$TERM2NAME
)

dotplot(res.kegg,showCategory = 15) 
enrichplot::cnetplot(res.kegg)

res.sim <- enrichplot::pairwise_termsim(res.kegg)

enrichplot::emapplot(res.sim)
